title: Celestial Emporium of Benevolent Knowledge
url: "https://benevolentknowledge.com"
baseurl: ""

markdown: kramdown
permalink: /blog/:slug/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
